import { Inter } from "next/font/google";
import "./globals.css";
import { HomePageProvider } from "./contexts/HomePageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HomePageProvider>
          {children}
        </HomePageProvider>
      </body>
    </html>
  );
}
